CREATE TABLE IF NOT EXISTS public."market_data" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "symbol" text NOT NULL,
    "timeframe" text NOT NULL,
    "ts" timestamptz NOT NULL,
    "open" numeric(18, 8) NOT NULL,
    "high" numeric(18, 8) NOT NULL,
    "low" numeric(18, 8) NOT NULL,
    "close" numeric(18, 8) NOT NULL,
    "volume" numeric(30, 10) NOT NULL
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'market_data'
          AND column_name = 'id'
          AND data_type <> 'bigint'
    ) THEN
        ALTER TABLE public."market_data" RENAME COLUMN "id" TO "id_uuid";
    END IF;
END
$$;

ALTER TABLE public."market_data" DROP CONSTRAINT IF EXISTS market_data_pkey;

ALTER TABLE public."market_data"
    ADD COLUMN IF NOT EXISTS "id" bigint GENERATED BY DEFAULT AS IDENTITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'market_data_pkey'
    ) THEN
        ALTER TABLE public."market_data" ADD CONSTRAINT market_data_pkey PRIMARY KEY ("id");
    END IF;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'market_data'
          AND column_name = 'symbol'
          AND data_type <> 'text'
    ) THEN
        ALTER TABLE public."market_data" ALTER COLUMN "symbol" TYPE text;
    END IF;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'market_data'
          AND column_name = 'timeframe'
          AND data_type <> 'text'
    ) THEN
        ALTER TABLE public."market_data" ALTER COLUMN "timeframe" TYPE text;
    END IF;
END
$$;

ALTER TABLE public."market_data" ADD COLUMN IF NOT EXISTS "ts" timestamptz;
ALTER TABLE public."market_data" ADD COLUMN IF NOT EXISTS "open" numeric(18, 8);
ALTER TABLE public."market_data" ADD COLUMN IF NOT EXISTS "high" numeric(18, 8);
ALTER TABLE public."market_data" ADD COLUMN IF NOT EXISTS "low" numeric(18, 8);
ALTER TABLE public."market_data" ADD COLUMN IF NOT EXISTS "close" numeric(18, 8);
ALTER TABLE public."market_data" ADD COLUMN IF NOT EXISTS "volume" numeric(30, 10);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'market_data'
          AND column_name = 'volume'
          AND data_type = 'numeric'
          AND (numeric_precision <> 30 OR numeric_scale <> 10)
    ) THEN
        ALTER TABLE public."market_data"
            ALTER COLUMN "volume" TYPE numeric(30, 10)
            USING "volume"::numeric(30, 10);
    END IF;
END
$$;

UPDATE public."market_data"
SET
    "ts" = COALESCE("ts", "updated_at", NOW()),
    "open" = COALESCE("open", "price"),
    "high" = COALESCE("high", "high_24h", "price"),
    "low" = COALESCE("low", "low_24h", "price"),
    "close" = COALESCE("close", "price"),
    "volume" = COALESCE("volume", 0)
WHERE
    "ts" IS NULL
    OR "open" IS NULL
    OR "high" IS NULL
    OR "low" IS NULL
    OR "close" IS NULL
    OR "volume" IS NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'market_data'
          AND column_name = 'ts'
          AND is_nullable = 'YES'
    ) THEN
        ALTER TABLE public."market_data" ALTER COLUMN "ts" SET NOT NULL;
    END IF;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'market_data'
          AND column_name = 'open'
          AND is_nullable = 'YES'
    ) THEN
        ALTER TABLE public."market_data" ALTER COLUMN "open" SET NOT NULL;
    END IF;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'market_data'
          AND column_name = 'high'
          AND is_nullable = 'YES'
    ) THEN
        ALTER TABLE public."market_data" ALTER COLUMN "high" SET NOT NULL;
    END IF;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'market_data'
          AND column_name = 'low'
          AND is_nullable = 'YES'
    ) THEN
        ALTER TABLE public."market_data" ALTER COLUMN "low" SET NOT NULL;
    END IF;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'market_data'
          AND column_name = 'close'
          AND is_nullable = 'YES'
    ) THEN
        ALTER TABLE public."market_data" ALTER COLUMN "close" SET NOT NULL;
    END IF;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'market_data'
          AND column_name = 'volume'
          AND is_nullable = 'YES'
    ) THEN
        ALTER TABLE public."market_data" ALTER COLUMN "volume" SET NOT NULL;
    END IF;
END
$$;

ALTER TABLE public."market_data" DROP COLUMN IF EXISTS "price";
ALTER TABLE public."market_data" DROP COLUMN IF EXISTS "change_24h";
ALTER TABLE public."market_data" DROP COLUMN IF EXISTS "high_24h";
ALTER TABLE public."market_data" DROP COLUMN IF EXISTS "low_24h";
ALTER TABLE public."market_data" DROP COLUMN IF EXISTS "updated_at";
ALTER TABLE public."market_data" DROP COLUMN IF EXISTS "id_uuid";

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'market_data_symbol_timeframe_ts_uniq'
    ) THEN
        ALTER TABLE public."market_data"
            ADD CONSTRAINT market_data_symbol_timeframe_ts_uniq UNIQUE ("symbol", "timeframe", "ts");
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_market_data_symbol_timeframe ON public."market_data" ("symbol", "timeframe");
